logger:
  level: trace
  log: /var/log/byconity/out.log
  errorlog: /var/log/byconity/err.log
  testlog: /var/log/byconity/test.log
  size: 1000M
  count: 10
listen_host: "0.0.0.0"
path: /var/byconity/
timezone: Europe/Moscow
catalog:
  name_space: default
perQuery: 1
catalog_service:
  type: fdb
  fdb:
    cluster_file: /config/fdb.cluster
resource_manager:
  port: 28989
  vws:
    vw:
      - name: vw_default
        type: default
        num_workers: 0
        worker_groups:
          worker_group:
            name: wg_default
            type: Physical
      - name: vw_write
        type: write
        num_workers: 0
        worker_groups:
          worker_group:
            name: wg_write
            type: Physical
service_discovery:
  mode: local
  cluster: default
  disable_cache: false
  cache_timeout: 5
  server:
    psm: data.cnch.server
    node:
      - host: server-0
        hostname: server-0
        ports:
          port:
            - name: PORT2
              value: 21557
            - name: PORT1
              value: 30605
            - name: PORT0
              value: 52145
            - name: PORT4
              value: 27651
            - name: PORT3
              value: 45443
            - name: PORT5
              value: 47447
            - name: PORT6
              value: 60611
      - host: server-1
        hostname: server-1
        ports:
          port:
            - name: PORT2
              value: 21557
            - name: PORT1
              value: 30605
            - name: PORT0
              value: 52145
            - name: PORT4
              value: 27651
            - name: PORT3
              value: 45443
            - name: PORT5
              value: 47447
            - name: PORT6
              value: 60611
  resource_manager:
    psm: data.cnch.resource_manager
    node:
      host: resource-manager-0
      hostname: resource-manager-0
      ports:
        port:
          name: PORT0
          value: 28989
  daemon_manager:
    psm: data.cnch.daemon_manager
    node:
      host: daemon-manager-0
      hostname: daemon-manager-0
      ports:
        port:
          name: PORT0
          value: 17553
  tso:
    psm: data.cnch.tso
    node:
      host: tso-0
      hostname: tso-0
      ports:
        port:
          - name: PORT0
            value: 18845
          - name: PORT2
            value: 9181
catalog:
  name_space: default
catalog_service:
  type: fdb
  fdb:
    cluster_file: /config/fdb.cluster
hdfs_addr: "hdfs://hdfs-namenode:9000"
