version: '3.3'

services:
  minio:
    ports:
      - 19001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    image: quay.io/minio/minio
    volumes:
      - ./data:/data'
    command: server /data --console-address ":9001"
    networks:
      - byconity-net
  
  # Create a default bucket.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/part-tools;
      /usr/bin/mc policy set public myminio/part-tools;
      /usr/bin/mc mb myminio/cnch;
      /usr/bin/mc policy set public myminio/cnch;
      exit 0;
      "
    networks:
      - byconity-net

  server: 
    depends_on:
      - minio
      - tso
    volumes:
      - ${CNCH_BINARY_PATH}/:/opt/byconity/bin/:ro
      - ./test_output/server/:/var/log/byconity/:rw
      - ./s3/:/config/:ro

  tso:
    volumes:
      - ${CNCH_BINARY_PATH}/:/opt/byconity/bin/:ro
      - ./test_output/tso/:/var/log/byconity/:rw
      - ./s3/:/config/:ro
    depends_on:
      - fdb
      - minio

  worker-write:
    volumes:
      - ${CNCH_BINARY_PATH}/:/opt/byconity/bin/:ro
      - ./s3/:/config/:ro
      - ./test_output/worker-write/:/var/log/byconity/:rw

  worker-default:
    volumes:
      - ./s3/:/config/:ro
      - ./test_output/worker-default/:/var/log/byconity/:rw
      - ${CNCH_BINARY_PATH}/:/opt/byconity/bin/:ro
      
  daemon-manager:
    volumes:
      - ./s3/:/config/:ro
      - ${CNCH_BINARY_PATH}/:/opt/byconity/bin/:ro
      - ./test_output/daemon-manager/:/var/log/byconity/:rw
