logger:
  level: trace
  log: /var/log/byconity/out.log
  errorlog: /var/log/byconity/err.log
  testlog: /var/log/byconity/test.log
  size: 1000M
  count: 10
http_port: 21557
rpc_port: 30605
tcp_port: 52145
ha_tcp_port: 26247
exchange_port: 47447
exchange_status_port: 60611
interserver_http_port: 30491
listen_host: "0.0.0.0"
cnch_type: worker
max_connections: 4096
keep_alive_timeout: 3
max_concurrent_queries: 200
uncompressed_cache_size: 8589934592
mark_cache_size: 5368709120
path: /var/byconity/
tmp_path: /var/byconity/tmp_data/
users_config: /config/users.yml
default_profile: default
default_database: default
timezone: Europe/Moscow
mlock_executable: false
macros:
  "-incl": macros
  "-optional": true
builtin_dictionaries_reload_interval: 3600
max_session_timeout: 3600
default_session_timeout: 60
dictionaries_config: "*_dictionary.xml"
format_schema_path: /var/byconity/format_schemas/
perQuery: 1
storage_configuration:
  disks:
    local_disk:
      path: /var/byconity/data/
      type: local
    s3_disk:
      path: data123/
      type: s3
      endpoint: http://minio:9000
      bucket: cnch
      ak_id: minio
      ak_secret: minio123
      is_virtual_hosted_style: false
  policies:
    default:
      volumes:
        local:
          default: local_disk
          disk: local_disk
    cnch_default_hdfs:
      volumes:
        s3:
          default: s3_disk
          disk: s3_disk
  # To avoid break hard-coded test cases.
  cnch_default_policy: cnch_default_hdfs
merge_tree:
  old_parts_lifetime: 0
  ttl_for_trash_items: 30
cnch_kafka_log:
  database: cnch_system
  table: cnch_kafka_log
  flush_max_row_count: 10000
  flush_interval_milliseconds: 7500
cnch_unique_table_log:
  database: cnch_system
  table: cnch_unique_table_log
  flush_max_row_count: 10000
  flush_interval_milliseconds: 7500
query_log:
  database: system
  table: query_log
  flush_interval_milliseconds: 15000
  partition_by: event_date
part_allocation_algorithm: 1
consistent_hash_ring:
  num_replicas: 16
  num_probes: 21
  load_factor: 1.3
cnch_config: /config/cnch-config.yml
sensitive_permission_tenants: 1234
additional_services:
  FullTextSearch: true
