CREATE DATABASE IF NOT EXISTS test1;

DROP TABLE IF EXISTS test1.t1;

CREATE TABLE test1.t1 (a Int32, b Int32) ENGINE = CnchMergeTree() ORDER BY a;

INSERT INTO test1.t1 VALUES(1,2)(2,3);

SELECT t1.* FROM test1.t1;
SELECT test1.t1.* FROM test1.t1;

DROP TABLE IF EXISTS test1.t1;

DROP DATABASE IF EXISTS test1;