SELECT (SELECT 1) IN (SELECT 1);
SELECT ((SELECT 1) IN (SELECT 1)) IN (SELECT 1);
SELECT (((SELECT 1) + (SELECT 1) IN (SELECT 1)) IN (SELECT 1)) IN (SELECT 1);
SELECT ((SELECT 1) + (toUInt64(rand()) % 100 + 1) IN (SELECT 1)) IN (SELECT 1);

SELECT
  (SELECT 1) IN (SELECT 1),
  ((SELECT 1) IN (SELECT 1)) IN (SELECT 1),
  (((SELECT 1) + (SELECT 1) IN (SELECT 1)) IN (SELECT 1)) IN (SELECT 1),
  ((SELECT 1) + (toUInt64(rand()) % 100 + 1) IN (SELECT 1)) IN (SELECT 1);
