SET enable_optimizer = 1;

DROP PREPARED STATEMENT IF EXISTS prep1;
DROP PREPARED STATEMENT IF EXISTS prep2;
DROP PREPARED STATEMENT IF EXISTS prep3;

CREATE PREPARED STATEMENT IF NOT EXISTS prep1 AS
SELECT count()
FROM (SELECT number FROM system.numbers LIMIT 10)
WHERE number < [x: UInt32];

SHOW PREPARED STATEMENTS;

EXPLAIN PREPARED STATEMENT prep1;

SHOW CREATE PREPARED STATEMENT prep1;

CREATE PREPARED STATEMENT OR REPLACE prep1 AS
SELECT count()
FROM (SELECT number FROM system.numbers LIMIT 10)
WHERE number < [i: UInt32];

EXECUTE PREPARED STATEMENT prep1 USING i = 1;
EXECUTE PREPARED STATEMENT prep1 USING i = 5;
EXECUTE PREPARED STATEMENT prep1 USING foo = 'bar'; -- { serverError 4080 }

DROP PREPARED STATEMENT IF EXISTS prep1;

-- test settings effect
SET iterative_optimizer_timeout=111111;

CREATE PREPARED STATEMENT prep2 AS
SELECT value FROM system.settings WHERE name = 'iterative_optimizer_timeout';

CREATE PREPARED STATEMENT prep3 AS
SELECT value FROM system.settings WHERE name = 'iterative_optimizer_timeout'
SETTINGS iterative_optimizer_timeout=333333;

SET iterative_optimizer_timeout=222222;

EXECUTE PREPARED STATEMENT prep2;
EXECUTE PREPARED STATEMENT prep3;
EXECUTE PREPARED STATEMENT prep3 SETTINGS iterative_optimizer_timeout=444444;

SHOW PREPARED STATEMENTS;

DROP PREPARED STATEMENT IF EXISTS prep2;
DROP PREPARED STATEMENT IF EXISTS prep3;
