if(NOT EXISTS "${ClickHouse_SOURCE_DIR}/contrib/bytekv4cpp/bytekv/client.h")
    if(USE_INTERNAL_BYTEKV_LIBRARY)
        message(WARNING "submodule contrib/bytekv4cpp is missing. to fix try run: \n git submodule update --init --recursive")
        set(USE_INTERNAL_BYTEKV_LIBRARY 0)
    endif()
    set(MISSING_INTERNAL_BYTEKV_LIBRARY 1)
endif()

if(NOT MISSING_INTERNAL_BYTEKV_LIBRARY)
    set(BYTEKV_INCLUDE_DIR "${ClickHouse_SOURCE_DIR}/contrib/bytekv4cpp/bytekv" "${ClickHouse_BINARY_DIR}/contrib/bytekv4cpp/thirdparty/brpc/output/include" CACHE INTERNAL "")
    set(USE_INTERNAL_BYTEKV_LIBRARY 1)
    set(BYTEKV_LIBRARY bytekv)
    set(MSGPACK_BUILD_TESTS OFF CACHE BOOL "turn off test" FORCE)
    set(MSGPACK_BUILD_EXAMPLES OFF CACHE BOOL "turn off examples" FORCE)
endif()

if(BYTEKV_LIBRARY AND BYTEKV_INCLUDE_DIR)
    set(USE_BYTEKV 1)
endif()

message(STATUS "Using bytekv=${USE_BYTEKV}: ${BYTEKV_INCLUDE_DIR} : ${BYTEKV_LIBRARY}")