USE test;
DROP TABLE IF EXISTS test.CnchMergeTree;

CREATE TABLE test.CnchMergeTree (x UInt64) ENGINE = CnchMergeTree ORDER BY x;
INSERT INTO test.CnchMergeTree VALUES (1);

SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM test.CnchMergeTree WHERE x IN (SELECT * FROM numbers(10000000))))))))))));

SET force_primary_key = 1;

SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM test.CnchMergeTree WHERE x IN (SELECT * FROM numbers(10000000))))))))))));

DROP TABLE test.CnchMergeTree;
