SET send_logs_level = 'none';



DROP TABLE IF EXISTS tab3;
DROP TABLE IF EXISTS tab4;

DROP MASKING POLICY IF EXISTS mask_1;
DROP MASKING POLICY IF EXISTS mask_2;

CREATE TABLE tab3 (s1 String) ENGINE = CnchMergeTree() PARTITION BY `s1` PRIMARY KEY `s1` ORDER BY `s1`;
CREATE TABLE tab4 (s2 String) ENGINE = CnchMergeTree() PARTITION BY `s2` PRIMARY KEY `s2` ORDER BY `s2`;

CREATE MASKING POLICY mask_1 AS (val String) -> CASE WHEN val IN (SELECT s2 FROM tab4) THEN '**' ELSE val END;
CREATE MASKING POLICY mask_2 AS (val String) -> CASE WHEN val IN (SELECT s1 FROM tab3) THEN '**' ELSE val END;

INSERT INTO tab3 VALUES ('a'), ('b');
INSERT INTO tab4 VALUES ('b'), ('c');

SELECT * FROM tab3 ORDER BY s1;

ALTER TABLE tab3 MODIFY COLUMN s1 SET MASKING POLICY mask_1;

SELECT * FROM tab3 ORDER BY s1;

ALTER TABLE tab4 MODIFY COLUMN s2 SET MASKING POLICY mask_2;

-- recursive dependency
SELECT * FROM tab3 ORDER BY s1; -- { serverError 162 }

ALTER TABLE tab3 MODIFY COLUMN s1 UNSET MASKING POLICY;
ALTER TABLE tab4 MODIFY COLUMN s2 UNSET MASKING POLICY;

DROP MASKING POLICY IF EXISTS mask_1;
DROP MASKING POLICY IF EXISTS mask_2;

DROP TABLE IF EXISTS tab3;
DROP TABLE IF EXISTS tab4;
