logger:
  level: trace
  log: /var/byconity/out.log
  errorlog: /var/byconity/err.log
  testlog: /var/byconity/test.log
  size: 1000M
  count: 10
path: /var/byconity/
timezone: Asia/Shanghai
catalog_service:
  type: fdb
  fdb:
    cluster_file: /config/fdb.cluster
service_discovery:
  mode: local
  cluster: default
  disable_cache: false
  cache_timeout: 5
  server:
    psm: data.cnch.server
    node:
      host: server-0
      hostname: server-0
      ports:
        port:
        -
          name: PORT2
          value: 21557
        -
          name: PORT1
          value: 30605
        -
          name: PORT0
          value: 52145
        -
          name: PORT4
          value: 27651
        -
          name: PORT3
          value: 45443
        -
          name: PORT5
          value: 47447
        -
          name: PORT6
          value: 60611
  tso:
    psm: data.cnch.tso
    node:
      host: tso-0
      hostname: tso-0
      ports:
        port:
        -
          name: PORT0
          value: 18845
        -
          name: PORT2
          value: 9181

storage_configuration:
  disks:
    hdfs_disk:
      path: /user/clickhouse/
      type: bytehdfs
    local_disk:
      path: /var/byconity/data/
      type: local
  policies:
    default:
      volumes:
        hdfs:
          default: hdfs_disk
          disk: hdfs_disk
        local:
          default: local_disk
          disk: local_disk

daemon_manager:
  port: 17553
  daemon_jobs:
    job:
    -
      name: PART_GC
      interval: 10000
      disable: 0
    -
      name: PART_MERGE
      interval: 10000
      disable: 0
    -
      name: CONSUMER
      interval: 10000
      disable: 0
    -
      name: GLOBAL_GC
      interval: 5000
      disable: 0
    -
      name: PART_CLUSTERING
      interval: 30000
      disable: 0
    -
      name: DEDUP_WORKER
      interval: 3000
      disable: 0
    - 
      name: TXN_GC
      interval: 3000
      disable: 0

hdfs_addr: "hdfs://hdfs-namenode:9000"
cnch_config: "/config/cnch-config.yml"
cnch_data_retention_time_in_sec: 0
s3_gc_batch_size: 10
