SELECT CASE 1 WHEN 1 THEN 'a' ELSE NULL END;
SELECT CASE 1 WHEN 2 THEN 'b' ELSE NULL END;
SELECT CASE 1 WHEN toNullable(1) THEN 'a' ELSE NULL END;
SELECT CASE toNullable(1) WHEN 1 THEN 'a' ELSE NULL END;
SELECT CASE toNullable(1) WHEN toNullable(1) THEN 'a' ELSE NULL END;
