-- drop database if EXISTS 002_merge_and_complex_json;
-- create database 002_merge_and_complex_json;
-- use 002_merge_and_complex_json;
SET allow_experimental_object_type = 1;
set describe_extend_object_types=1;
SET block_json_query_in_optimizer = 0;
CREATE TABLE if not exists t_alter_ids_8(
            `id` UInt64,
            `date` Date,
            `json` JSON
) ENGINE = CnchMergeTree ORDER BY id partition by date;
system stop merges t_alter_ids_8;
insert into t_alter_ids_8 values(1, '2023-12-13', '{"_id": "65790d3f5ee1fd8bdefd1e8e","index": 1,"guid": "534c7df4-78f6-4f3f-b631-70af0d14a309","isActive": true,"balance": "$2,491.01","picture": "http://placehold.it/32x32","age": 36,"eyeColor": "green","name": "Macias Snow","gender": "male","company": "TRASOLA","email": "maciassnow@trasola.com","phone": "+1 (961) 529-2559","address": "288 Hinckley Place, Carlos, Florida, 6654","about": "Veniam cillum magna eu ut occaecat. Consectetur aliqua elit enim aliqua. Nulla dolore sint deserunt enim magna eiusmod do. Pariatur eiusmod consequat ea excepteur culpa ipsum duis esse esse.","registered": "2018-05-28T01:27:13 -08:00","latitude": -48.198628,"longitude": 166.730178,"tags": ["commodo", "velit", "reprehenderit","commodo","quis","Lorem","Lorem"],"friends": [{"id": 0,"name": "Blanca Lawson"},{"id": 1,"name":"Karyn Russell"},  {"id": 2,"name":"Ola Joyce"}],"greeting": "Hello, Macias Snow! You have 8 unread messages.","favoriteFruit": "banana"}');
insert into t_alter_ids_8 values(2, '2023-12-13', '{"_id": "65790d3f5ee1fd8bdefd1e8e","index": 2,"guid": "534c7df4-78f6-4f3f-b631-70af0d14a309","isActive": true,"balance": "$2,491.01","picture": "http://placehold.it/32x32","age": 36,"eyeColor": "green","name": "Macias Snow","gender": "male","company": "TRASOLA","email": "maciassnow@trasola.com","phone": "+1 (961) 529-2559","address": "288 Hinckley Place, Carlos, Florida, 6654","about": "Veniam cillum magna eu ut occaecat. Consectetur aliqua elit enim aliqua. Nulla dolore sint deserunt enim magna eiusmod do. Pariatur eiusmod consequat ea excepteur culpa ipsum duis esse esse.","registered": "2018-05-28T01:27:13 -08:00","latitude": -48.198628,"longitude": 166.730178,"tags": ["commodo", "velit", "reprehenderit","commodo","quis","Lorem","Lorem"],"friends": [{"id": 0,"name": "Blanca Lawson"},{"id": 1,"name":"Karyn Russell"},  {"id": 2,"name":"Ola Joyce"}],"greeting": "Hello, Macias Snow! You have 8 unread messages.","favoriteFruit": "banana"}');
insert into t_alter_ids_8 values(3, '2023-12-13', '{"_id": "65790d3f5ee1fd8bdefd1e8e","index": 3,"guid": "534c7df4-78f6-4f3f-b631-70af0d14a309","isActive": true,"balance": "$2,491.01","picture": "http://placehold.it/32x32","age": 36,"eyeColor": "green","name": "Macias Snow","gender": "male","company": "TRASOLA","email": "maciassnow@trasola.com","phone": "+1 (961) 529-2559","address": "288 Hinckley Place, Carlos, Florida, 6654","about": "Veniam cillum magna eu ut occaecat. Consectetur aliqua elit enim aliqua. Nulla dolore sint deserunt enim magna eiusmod do. Pariatur eiusmod consequat ea excepteur culpa ipsum duis esse esse.","registered": "2018-05-28T01:27:13 -08:00","latitude": -48.198628,"longitude": 166.730178,"tags": ["commodo", "velit", "reprehenderit","commodo","quis","Lorem","Lorem"],"friends": [{"id": 0,"name": "Blanca Lawson"},{"id": 1,"name":"Karyn Russell"},  {"id": 2,"name":"Ola Joyce"}],"greeting": "Hello, Macias Snow! You have 8 unread messages.","favoriteFruit": "banana"}');
insert into t_alter_ids_8 values(4, '2023-12-13', '{"_id": "65790d3f5ee1fd8bdefd1e8e","index": 4,"guid": "534c7df4-78f6-4f3f-b631-70af0d14a309","isActive": true,"balance": "$2,491.01","picture": "http://placehold.it/32x32","age": 36,"eyeColor": "green","name": "Macias Snow","gender": "male","company": "TRASOLA","email": "maciassnow@trasola.com","phone": "+1 (961) 529-2559","address": "288 Hinckley Place, Carlos, Florida, 6654","about": "Veniam cillum magna eu ut occaecat. Consectetur aliqua elit enim aliqua. Nulla dolore sint deserunt enim magna eiusmod do. Pariatur eiusmod consequat ea excepteur culpa ipsum duis esse esse.","registered": "2018-05-28T01:27:13 -08:00","latitude": -48.198628,"longitude": 166.730178,"tags": ["commodo", "velit", "reprehenderit","commodo","quis","Lorem","Lorem"],"friends": [{"id": 0,"name": "Blanca Lawson"},{"id": 1,"name":"Karyn Russell"},  {"id": 2,"name":"Ola Joyce"}],"greeting": "Hello, Macias Snow! You have 8 unread messages.","favoriteFruit": "banana"}');
insert into t_alter_ids_8 values(5, '2023-12-13', '{"_id": "65790d3f5ee1fd8bdefd1e8e","index": 5,"guid": "534c7df4-78f6-4f3f-b631-70af0d14a309","isActive": true,"balance": "$2,491.01","picture": "http://placehold.it/32x32","age": 36,"eyeColor": "green","name": "Macias Snow","gender": "male","company": "TRASOLA","email": "maciassnow@trasola.com","phone": "+1 (961) 529-2559","address": "288 Hinckley Place, Carlos, Florida, 6654","about": "Veniam cillum magna eu ut occaecat. Consectetur aliqua elit enim aliqua. Nulla dolore sint deserunt enim magna eiusmod do. Pariatur eiusmod consequat ea excepteur culpa ipsum duis esse esse.","registered": "2018-05-28T01:27:13 -08:00","latitude": -48.198628,"longitude": 166.730178,"tags": ["commodo", "velit", "reprehenderit","commodo","quis","Lorem","Lorem"],"friends": [{"id": 0,"name": "Blanca Lawson"},{"id": 1,"name":"Karyn Russell"},  {"id": 2,"name":"Ola Joyce"}],"greeting": "Hello, Macias Snow! You have 8 unread messages.","favoriteFruit": "banana"}');
insert into t_alter_ids_8 values(6, '2023-12-13', '{"_id": "65790d3f5ee1fd8bdefd1e8e","index": 6,"guid": "534c7df4-78f6-4f3f-b631-70af0d14a309","isActive": true,"balance": "$2,491.01","picture": "http://placehold.it/32x32","age": 36,"eyeColor": "green","name": "Macias Snow","gender": "male","company": "TRASOLA","email": "maciassnow@trasola.com","phone": "+1 (961) 529-2559","address": "288 Hinckley Place, Carlos, Florida, 6654","about": "Veniam cillum magna eu ut occaecat. Consectetur aliqua elit enim aliqua. Nulla dolore sint deserunt enim magna eiusmod do. Pariatur eiusmod consequat ea excepteur culpa ipsum duis esse esse.","registered": "2018-05-28T01:27:13 -08:00","latitude": -48.198628,"longitude": 166.730178,"tags": ["commodo", "velit", "reprehenderit","commodo","quis","Lorem","Lorem"],"friends": [{"id": 0,"name": "Blanca Lawson"},{"id": 1,"name":"Karyn Russell"},  {"id": 2,"name":"Ola Joyce"}],"greeting": "Hello, Macias Snow! You have 8 unread messages.","favoriteFruit": "banana"}');
select '----------------------before merge-------------------------------';
select count() from system.cnch_parts where database=currentDatabase() and table='t_alter_ids_8' and part_type='VisiblePart';
select json.index as index from t_alter_ids_8 order by index;
system start merges t_alter_ids_8;
set disable_optimize_final=0;
optimize table t_alter_ids_8 final;
SELECT sleepEachRow(3) FROM numbers(6) FORMAT Null;
select '-------------------after first merge-----------------------------';
select count() from system.cnch_parts where database=currentDatabase() and table='t_alter_ids_8' and part_type='VisiblePart';
select json.index as index from t_alter_ids_8 order by index;
drop table if exists t_alter_ids_8;
