drop table if exists prewhere_alias;
CREATE TABLE prewhere_alias (a UInt8,  b Int32,  c UInt8 ALIAS a,  d Int64 ALIAS b + 1, e Int32 alias a + b) ENGINE = CnchMergeTree ORDER BY tuple() SETTINGS enable_late_materialize = 1;
insert into prewhere_alias values (1, 1);
select '-';
select a from prewhere_alias where a = 1;
select b from prewhere_alias where a = 1;
select c from prewhere_alias where a = 1;
select d from prewhere_alias where a = 1;
select '-';
select a from prewhere_alias where b = 1;
select b from prewhere_alias where b = 1;
select c from prewhere_alias where b = 1;
select d from prewhere_alias where b = 1;
select '-';
select a from prewhere_alias where c = 1;
select b from prewhere_alias where c = 1;
select c from prewhere_alias where c = 1;
select d from prewhere_alias where c = 1;
select '-';
select a from prewhere_alias where d = 2;
select b from prewhere_alias where d = 2;
select c from prewhere_alias where d = 2;
select d from prewhere_alias where d = 2;
select '-';
select a from prewhere_alias where a;
select b from prewhere_alias where a;
select c from prewhere_alias where a;
select d from prewhere_alias where a;
select '-';
select a from prewhere_alias where c;
select b from prewhere_alias where c;
select c from prewhere_alias where c;
select d from prewhere_alias where c;
drop table if exists prewhere_alias;

