SELECT substr('helloworld', 6);
SELECT substr('helloworld' FROM 6);
SELECT substr('helloworld', 6, 3);
SELECT substr('helloworld' FROM 6 FOR 3);
SELECT SUBSTR('helloworld', 6);
SELECT SUBSTR('helloworld' FROM 6);
SELECT SUBSTR('helloworld', 6, 3);
SELECT SUBSTR('helloworld' FROM 6 FOR 3);
SELECT substring('helloworld', 6);
SELECT substring('helloworld' FROM 6);
SELECT substring('helloworld', 6, 3);
SELECT substring('helloworld' FROM 6 FOR 3);
SELECT SUBSTRING('helloworld', 6);
SELECT SUBSTRING('helloworld' FROM 6);
SELECT SUBSTRING('helloworld', 6, 3);
SELECT SUBSTRING('helloworld' FROM 6 FOR 3);
SELECT substr('', 6);
SELECT substr('' FROM 6);
SELECT substr('', 6, 3);
SELECT substr('' FROM 6 FOR 3);
SELECT SUBSTR('', 6);
SELECT SUBSTR('' FROM 6);
SELECT SUBSTR('', 6, 3);
SELECT SUBSTR('' FROM 6 FOR 3);
SELECT substring('', 6);
SELECT substring('' FROM 6);
SELECT substring('', 6, 3);
SELECT substring('' FROM 6 FOR 3);
SELECT SUBSTRING('', 6);
SELECT SUBSTRING('' FROM 6);
SELECT SUBSTRING('', 6, 3);
SELECT SUBSTRING('' FROM 6 FOR 3);