SET enable_optimizer = 1;
SET enable_distinct_to_aggregate = 0;
SELECT DISTINCT a FROM (SELECT 1 AS a UNION ALL SELECT 1 UNION ALL SELECT 1);
SELECT 1 UNION DISTINCT SELECT 1 UNION DISTINCT SELECT 1;
