DROP TABLE IF EXISTS aeolus_data_table_2_1634191_prod;
CREATE TABLE aeolus_data_table_2_1634191_prod(
    `user_id` Int64,
    `product_id` Int64,
    `p_date` Date,
    `mall_entrance_type` Nullable(String),
    `is_content_new_user` Nullable(Int32),
    `is_homepage_new_user` Nullable(Int32),
    `is_seckill_pay_1year` Nullable(Int64),
    `is_order_center_pay` Nullable(Int32),
    `reserve_label` Nullable(String),
    `is_inchannel` Nullable(Int64),
    `is_reserve_1d` Nullable(Int32),
    `is_reserve_2d` Nullable(Int32),
    `user_group_label_name` Nullable(String),
    `age` Nullable(String),
    `gender` Nullable(String),
    `consumption_level` Nullable(String),
    `consumption_level_new` Nullable(String),
    `product_source` Nullable(String),
    `product_name` Nullable(String),
    `okr_brand_id` Nullable(Int64),
    `std_brand_name` Nullable(String),
    `brand_level` Nullable(String),
    `shop_id` Nullable(Int64),
    `shop_name` Nullable(String),
    `first_cid_new` Nullable(Int64),
    `first_name_new` Nullable(String),
    `second_cid_new` Nullable(Int64),
    `second_name_new` Nullable(String),
    `leaf_cid_new` Nullable(Int64),
    `leaf_name_new` Nullable(String),
    `vertical_category_new_id` Nullable(Int64),
    `vertical_category_new` Nullable(String),
    `vertical_category_code_new` Nullable(String),
    `vert_cate_name` Nullable(String),
    `vert_cate_id` Nullable(Int64),
    `vert_cate_code` Nullable(String),
    `content_type` Nullable(String),
    `enter_from` Nullable(String),
    `pit` Nullable(String),
    `seckill_module` Nullable(String),
    `seckill_tab_id` Nullable(Int64),
    `seckill_status` Nullable(String),
    `is_seckill_coupon` Nullable(Int64),
    `sku_max_price` Nullable(Int64),
    `sku_min_price` Nullable(Int64),
    `ecop_industry_id` Nullable(Int64),
    `ecop_industry_code` Nullable(String),
    `ecop_industry_name` Nullable(String),
    `emp_name` Nullable(String),
    `first_vbline_id` Nullable(Int64),
    `first_vbline_code` Nullable(String),
    `first_vbline_name` Nullable(String),
    `second_vbline_id` Nullable(Int64),
    `second_vbline_code` Nullable(String),
    `second_vbline_name` Nullable(String),
    `third_vbline_id` Nullable(Int64),
    `third_vbline_code` Nullable(String),
    `third_vbline_name` Nullable(String),
    `fourth_vbline_id` Nullable(Int64),
    `fourth_vbline_code` Nullable(String),
    `fourth_vbline_name` Nullable(String),
    `leaf_vbline_id` Nullable(Int64),
    `leaf_vbline_code` Nullable(String),
    `leaf_vbline_name` Nullable(String),
    `prod_show_cnt` Nullable(Int64),
    `prod_click_cnt` Nullable(Int64),
    `book_click_cnt` Nullable(Int64),
    `seckill_module_clk_cnt_1d` Nullable(Int64),
    `pay_order_cnt` Nullable(Int64),
    `pay_amt` Nullable(Int64),
    `sale_cnt` Nullable(Int64),
    `mall_pay_order_cnt` Nullable(Int64),
    `mall_pay_amt` Nullable(Int64),
    `mall_sale_cnt` Nullable(Int64),
    `remark_order_cnt_14d` Nullable(Int64),
    `good_cmnt_order_cnt_14d` Nullable(Int64),
    `bad_cmnt_order_cnt_14d` Nullable(Int64),
    `first_cmnt_bad_cmnt_order_cnt_14d` Nullable(Int64),
    `good_cmnt_order_cnt_30d` Nullable(Int64),
    `bad_cmnt_order_cnt_30d` Nullable(Int64),
    `quality_return_order_cnt_14d` Nullable(Int64),
    `prod_quality_return_order_cnt_14d` Nullable(Int64),
    `logistics_quality_return_order_cnt_14d` Nullable(Int64),
    `complaint_ticket_cnt_14d` Nullable(Int64),
    `campaign_platform_cost_amt` Nullable(Int64),
    `channel_pay_layer_p1d` Nullable(String),
    `channel_visit_layer_p1d` Nullable(String),
    `ecop_industry_user_ltv_level` Nullable(String),
    `previous_page` Nullable(String),
    `channel_visit_cnt_1d` Nullable(Int64),
    `channel_entrance_show_cnt_1d` Nullable(Int64),
    `channel_entrance_clk_cnt_1d` Nullable(Int64),
    `price_range` Nullable(String),
    `settle_pay_ord_amt_p14d` Nullable(Int64),
    `platform_coupon_amt_1d` Nullable(Int64),
    `first_level_source` Nullable(String),
    `second_level_source` Nullable(String),
    `mall_pay_layer_platform_mall_p1d` Nullable(String),
    `mall_pay_layer_platform_mall_p1d_v2` Nullable(String),
    `date` Nullable(String),
    `app_name` Nullable(String),
    `tab_clk_cnt_1d` Nullable(Int64),
    `ecom_page_slide_cnt_1d` Nullable(Int64),
    `subscribe_button_clk_cnt_1d` Nullable(Int64),
    `search_entrance_clk_1d` Nullable(Int64),
    `ecom_page_cross_slide_cnt_1d` Nullable(Int64),
    `banner_clk_1d` Nullable(Int64),
    `expl_seckill_entrance_clk_cnt_1d` Nullable(Int64),
    `ecommerce_module_entrace_clk_cnt_1d` Nullable(Int64),
    `chnl_clk_cnt_1d` Nullable(Int64),
    `ecom_button_show_cnt_1d` Nullable(Int64),
    `ecom_coupon_clk_cnt_1d` Nullable(Int64),
    `chnl_valid_bhv_visit_cnt_1d` Nullable(Int64),
    `guess_prod_clk_cnt_1d` Nullable(Int64),
    `platform_coupon_pay_ord_amt_1d` Nullable(Int64),
    `campaign_platform_pay_ord_amt_1d` Nullable(Int64),
    `platform_coupon_pay_ord_cnt_1d` Nullable(Int64),
    `campaign_platform_pay_ord_cnt_1d` Nullable(Int64),
    `order_cnt_threshold` Nullable(Int64),
    `dlevel_cate_type` Nullable(String),
    `avg_day_unfreeprod_pay_ord_cnt_30d` Nullable(Float64),
    `shop_dlevel` Nullable(Int64),
    `dlevel_cate` Nullable(String),
    `activity_start_time` Nullable(Int64),
    `activity_end_time` Nullable(Int64),
    `effective_min_price` Nullable(Float64),
    `effective_max_price` Nullable(Float64),
    `activity_id` Nullable(Int64),
    `is_nn_activity` Nullable(Int64),
    `channel_pay_ord_cnt_layer_30d` Nullable(String),
    `seckill_module_ch_name` Nullable(String),
    `mall_new_ent_channel_pay_layer_p1d` Nullable(String),
    `show_price` Nullable(Int64),
    `show_sku_id` Nullable(Int64),
    `discount_price` Nullable(Float64),
    `third_module` Nullable(String),
    `newent_nature_visit_days_layer_30d` Nullable(String),
    `warehouse_id` Nullable(Int64),
    `new_age_five_groups` Nullable(String),
    `date[dm_prof_user_std_early_df]` Nullable(String),
    `first_tab_id` Nullable(Int64),
    `first_tab_name` Nullable(String),
    `channel_new_entrance_user_layer_v2` Nullable(String),
    `is_algo_schedule` Nullable(Int64),
    `date[dim_prd_product_extend_df]` Nullable(String),
    `complex_brand_s_level_v2` Nullable(String)
) ENGINE = CnchMergeTree 
PARTITION BY p_date
ORDER BY (user_id, product_id, intHash64(user_id)) SAMPLE BY intHash64(user_id) cluster by user_id into 20 buckets TTL p_date + toIntervalDay(701);

set enable_split_countd_to_state_merge=1;
set enable_case_when_prop=1;
set enable_optimizer=1;
set enable_expand_distinct_optimization=0;
set enable_mark_distinct_optimzation=0;

EXPLAIN
SELECT
    formatDateTime(toStartOfInterval(p_date, toIntervalDay(1)), '%Y-%m-%d') AS _time_8_1_1700037075152,
    CAST(countDistinct(multiIf(channel_visit_cnt_1d > 0, user_id, NULL)), 'Nullable(Int64)') AS _1700037075267,
    sum(pay_order_cnt) AS _sum_1700037075233,
    sum((campaign_platform_cost_amt / 100) + (CAST(platform_coupon_amt_1d, 'Nullable(Int64)') / 100)) AS _sum_1700037153441,
    sum((campaign_platform_cost_amt / 100) + (CAST(platform_coupon_amt_1d, 'Nullable(Int64)') / 100)) / (sum((campaign_platform_cost_amt / 100) + (CAST(platform_coupon_amt_1d, 'Nullable(Int64)') / 100)) + sum(pay_amt / 100)) AS _1700043852272
FROM aeolus_data_table_2_1634191_prod
WHERE ((p_date >= '2024-08-13') AND (p_date <= '2024-08-20')) AND (app_name = 'aweme') AND ((previous_page LIKE '%UG_MIAOSHA_DNLH_2024_NN_CSJ%') OR (previous_page LIKE '%tfx_feeds_ad_buy_limited_offer_CSJ%'))
GROUP BY formatDateTime(toStartOfInterval(p_date, toIntervalDay(1)), '%Y-%m-%d')
ORDER BY _time_8_1_1700037075152 ASC
LIMIT 1000;

DROP TABLE IF EXISTS aeolus_data_table_2_1634191_prod;