USE test;
SET enable_optimizer=0; -- can't find local replica in cluster settings

DROP TABLE IF EXISTS tob_apps;
DROP TABLE IF EXISTS tob_apps_all;
CREATE TABLE tob_apps (`app_id` UInt32, `app_name` String DEFAULT '', `app_version` String DEFAULT '', `device_id` String DEFAULT '', `device_model` String DEFAULT '', `device_brand` String DEFAULT '', `hash_uid` UInt64, `os_name` String DEFAULT '', `os_version` String DEFAULT '', `network_type` String DEFAULT '', `network_carrier` String DEFAULT '', `app_channel` String DEFAULT '', `user_register_ts` Nullable(UInt64), `server_time` UInt64, `time` UInt64, `event` String, `user_unique_id` String, `event_date` Date, `ab_version` Array(Int32), `tea_app_id` UInt32, `app_region` String DEFAULT '', `region` String DEFAULT '', `app_language` String DEFAULT '', `language` String DEFAULT '', `gender` String DEFAULT '', `age` String DEFAULT '', `string_params` Map(String, String), `int_params` Map(String, Int64), `float_params` Map(String, Float64), `string_profiles` Map(String, String), `int_profiles` Map(String, Int64), `float_profiles` Map(String, Float64), `user_id` String DEFAULT '', `ssid` String DEFAULT '', `string_item_profiles` Map(String, Array(String)), `int_item_profiles` Map(String, Array(Int64)), `float_item_profiles` Map(String, Array(Float64)), `content` String) ENGINE = MergeTree PARTITION BY (tea_app_id, event_date) ORDER BY (tea_app_id, event, event_date, hash_uid, user_unique_id) SAMPLE BY hash_uid SETTINGS index_granularity = 8192;
CREATE TABLE tob_apps_all (`app_id` UInt32, `app_name` String DEFAULT '', `app_version` String DEFAULT '', `device_id` String DEFAULT '', `device_model` String DEFAULT '', `device_brand` String DEFAULT '', `hash_uid` UInt64, `os_name` String DEFAULT '', `os_version` String DEFAULT '', `network_type` String DEFAULT '', `network_carrier` String DEFAULT '', `app_channel` String DEFAULT '', `user_register_ts` Nullable(UInt64), `server_time` UInt64, `time` UInt64, `event` String, `user_unique_id` String, `event_date` Date, `ab_version` Array(Int32), `tea_app_id` UInt32, `app_region` String DEFAULT '', `region` String DEFAULT '', `app_language` String DEFAULT '', `language` String DEFAULT '', `gender` String DEFAULT '', `age` String DEFAULT '', `string_params` Map(String, String), `int_params` Map(String, Int64), `float_params` Map(String, Float64), `string_profiles` Map(String, String), `int_profiles` Map(String, Int64), `float_profiles` Map(String, Float64), `user_id` String DEFAULT '', `ssid` String DEFAULT '', `string_item_profiles` Map(String, Array(String)), `int_item_profiles` Map(String, Array(Int64)), `float_item_profiles` Map(String, Array(Float64)), `content` String) ENGINE = Distributed(test_cluster_two_shards, 'test', 'tob_apps');
INSERT INTO tob_apps VALUES (208334,'rangers_5474_haoquvideo','1.0.4','70674577545','gionee m7','xx',4295538242597697608,'android','7.1.1','4g','xxx','promotion',1609599702,1609767161,1609599702236,'app_launch','655c1348-4ce8-48a7-b4c4-aebd4776fee8','2021-01-02',[],274474,'','','unknown','zh','m','31-40',{'session_id':'a213d469-8150-4a64-a2ce-ba98d857a8b6'},{'session_duration':170},{},{'activation_channel':'promotion','activation_type':'organic','app_channel':'unknown','app_language':'unknown','app_version':'unknown','browser':'unknown','browser_version':'unknown','client_ip':'xx.xx.xx.xx','custom_bd_did':'K2N6KPS42ZYJI7CBAHL4LHRPZJD7N45HIIEFNXCHQ6OXT7OLJB4Q01','custom_k_may_support':'false','custom_req_id':'c0e6ec3f-d6dc-4ed1-b938-cb71634eab67','custom_sdk_version_name':'5.4.2','custom_udid_list':'[{"slot_index":0,"id":"866402033899148","type":"unknown"},{"slot_index":1,"id":"866402038899143","type":"unknown"}]','device_ip':'xxx.xxx.xxx.xxx','device_model':'unknown','language':'zh','loc_city_id':'2038180','loc_country_id':'1814991','loc_province_id':'2036500','network_carrier':'unknown','network_type':'unknown','os_name':'unknown','os_version':'unknown','package':'com.nxtools.video.haoqu','region':'CN','resolution':'2160x1080','sdk_version':'5040290','sim_region':'cn','tz_name':'Asia/Shanghai','tz_offset':'28800','user_id':'1011154775719725','uuid':'kdXX0slGBWzjtUA8pUjlbQ=='},{'timezone':8,'update_version_code':10004,'user_is_login':0},{'custom_register_time':1609767161227,'custom_sdk_version_code':15039889},'1011154775719725','',{},{},{},'');

SELECT
    lastRangeCount(1, 30, 6)(ud) AS dau1,
    lastRangeCount(7, 30, 6)(ud) AS dau1_7,
    lastRangeCount(30, 30, 6)(ud) AS dau1_30
FROM
(
    SELECT userDistribution(1606492800, 86400, 36)(if(time > 2000000000, toUInt32(time / 1000), time), user_register_ts) AS ud
    FROM tob_apps_all
    WHERE (tea_app_id = 274474) AND (event = 'app_launch') AND (event_date >= '2020-11-28') AND (event_date <= '2021-01-02') AND (if(time > 2000000000, toUInt32(time / 1000), time) >= 1606492800) AND (if(time > 2000000000, toUInt32(time / 1000), time) <= 1609603199) AND ((ifNull(device_id, 'null') NOT IN ('null', '', '-1', '0')) AND (ifNull(os_name, 'null') IN ('ios', 'android')))
    GROUP BY hash_uid
);

DROP TABLE IF EXISTS tob_apps;
DROP TABLE IF EXISTS tob_apps_all;