CREATE TABLE t1 (id UInt32, t UInt32, cnt UInt32) ENGINE = MergeTree() ORDER BY id;
INSERT INTO t1 VALUES(1, 10, 100);
INSERT INTO t1 VALUES(2, 20, 200);
INSERT INTO t1 VALUES(3, 30, 300);
INSERT INTO t1 VALUES(4, 40, 400);
INSERT INTO t1 VALUES(5, 50, 500);

SELECT id, t,(sum(cnt) OVER (PARTITION BY id ORDER BY id ASC, t ASC RANGE UNBOUNDED PRECEDING)) from t1;
SELECT id, t,(sum(cnt) OVER (PARTITION BY id ORDER BY id ASC, t ASC ROWS BETWEEN 0 PRECEDING AND 0 PRECEDING)) from t1;
SELECT id, t,(sum(cnt) OVER (PARTITION BY id ORDER BY id ASC, t ASC ROWS BETWEEN 0 PRECEDING AND 0 PRECEDING EXCLUDE NO OTHERS)) from t1;
SELECT id, t,(sum(cnt) OVER (PARTITION BY id ORDER BY id ASC, t ASC ROWS BETWEEN 0 PRECEDING AND 0 PRECEDING EXCLUDE NO      OTHERS)) from t1;
